# Generated by Django 2.1.3 on 2018-12-14 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_car_rent_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='cars/%Y/%m/%d/')),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='photos',
        ),
        migrations.AddField(
            model_name='car',
            name='images',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars.CarImage'),
            preserve_default=False,
        ),
    ]
