# Generated by Django 2.1.2 on 2018-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_auto_20181021_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='owner',
            field=models.ForeignKey(on_delete=False, related_name='cars', to='Owners.Owner'),
        ),
        migrations.AlterField(
            model_name='car',
            name='photos',
            field=models.ImageField(blank=True, upload_to='cars/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
