# Generated by Django 2.1.3 on 2018-11-23 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20181123_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_type',
            field=models.ForeignKey(default=0, on_delete=False, to='cars.Rent_type'),
        ),
    ]
