# Generated by Django 2.1.2 on 2018-10-25 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0003_auto_20181025_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='owner',
        ),
    ]
