# Generated by Django 2.1.3 on 2018-12-15 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20181215_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimage',
            old_name='owner',
            new_name='car',
        ),
    ]
