# Generated by Django 2.1.3 on 2019-01-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferOrder',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('user_id', models.CharField(max_length=25)),
                ('user_phonenumber', models.CharField(max_length=25)),
                ('car_id', models.CharField(max_length=25)),
                ('starttime', models.DateTimeField()),
                ('city', models.CharField(max_length=25)),
                ('owner_id', models.CharField(max_length=25)),
                ('rent_type', models.CharField(choices=[('Hourly', 'Почасовая аренда'), ('Daily', 'Посуточная аренда'),
                                                        ('Long_term', 'Долгосрочная'), ('Transfer', 'Трансфер'),
                                                        ('Bus_rent', 'Аренда автобуса'),
                                                        ('Carwithdriver', 'Аренда авто с водителем')], max_length=25)),
                ('height', models.CharField(max_length=25)),
                ('width', models.CharField(max_length=25)),
                ('weight', models.CharField(max_length=25)),
                ('islong', models.CharField(max_length=25)),
                ('passengers', models.CharField(max_length=25)),
                ('stage1', models.BooleanField(default=False)),
                ('price', models.CharField(max_length=25)),
                ('stage2', models.BooleanField(default=False)),
                ('confirmation', models.BooleanField(default=False)),
            ],
        ),
    ]
