# Generated by Django 2.1.3 on 2018-11-28 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('city', models.CharField(default='Киев', max_length=25)),
                ('owner_type', models.CharField(choices=[('Private', 'Частное лицо'), ('Company', 'Организация')], default='Private', max_length=25)),
                ('photo', models.ImageField(default='photos/default.png', upload_to='photos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
