# Generated by Django 2.1.2 on 2018-10-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('owner_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phonenumber', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=25)),
                ('cash_account', models.CharField(max_length=25)),
                ('discount', models.CharField(max_length=25)),
                ('owner_type', models.CharField(choices=[('Private', 'Частное лицо'), ('Company', 'Организация')], max_length=25)),
                ('own_cars', models.CharField(max_length=25)),
                ('incoming_orders', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
            ],
        ),
    ]
