# Generated by Django 2.1.2 on 2018-11-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='cash_account',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
