# Generated by Django 2.1.3 on 2018-11-23 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_account', models.CharField(default=0, max_length=25)),
                ('registration_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('ident_code', models.CharField(default='', max_length=14)),
                ('owner_type', models.CharField(choices=[('Private', 'Частное лицо'), ('Company', 'Организация')], default='Private', max_length=25)),
                ('own_cars', models.CharField(default='', max_length=14)),
                ('incoming_orders', models.CharField(default='', max_length=25)),
                ('city', models.CharField(default='Киев', max_length=25)),
                ('approve', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
