# Generated by Django 2.1.2 on 2018-11-02 13:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('owner', '0002_auto_20181102_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='own_cars',
        ),
    ]
