# Generated by Django 2.1.2 on 2018-11-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('owner', '0005_auto_20181102_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='own_cars',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cars.Car'),
        ),
    ]
