# Generated by Django 2.1.2 on 2018-11-04 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('owner', '0006_auto_20181102_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_phonenumber', models.CharField(max_length=25)),
                ('carsinblacklistvin', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='owner',
            name='discount',
        ),
        migrations.AddField(
            model_name='owner',
            name='ident_code',
            field=models.CharField(default=0, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='registration_photo',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blacklist',
            name='blackownerid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owneridblack',
                                    to='owner.Owner'),
        ),
    ]
