# Generated by Django 2.1.2 on 2018-11-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('owner', '0007_auto_20181104_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='owner_phonenumber',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
