# Generated by Django 2.1.2 on 2018-11-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('owner', '0008_auto_20181104_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
