# Generated by Django 2.1.2 on 2018-11-09 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cars', '0006_remove_car_car_owner'),
        ('owner', '0009_owner_approve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_account', models.CharField(default=0, max_length=25)),
                ('registration_photo', models.ImageField(upload_to='')),
                ('ident_code', models.CharField(max_length=14)),
                ('owner_type',
                 models.CharField(choices=[('Private', 'Частное лицо'), ('Company', 'Организация')], max_length=25)),
                ('incoming_orders', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('approve', models.BooleanField(default=False)),
                ('own_cars',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='cars.Car')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='blacklist',
            name='blackownerid',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='own_cars',
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
