# Generated by Django 2.1.2 on 2018-11-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('owner', '0010_auto_20181109_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='own_cars',
            field=models.CharField(max_length=14),
        ),
    ]
