# Generated by Django 2.1.2 on 2018-11-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('owner', '0011_auto_20181115_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='registration_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
